# Generated by Django 5.2.5 on 2025-08-24 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('contact_info', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BaptizedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('baptism_date', models.DateField()),
                ('contact_info', models.CharField(blank=True, max_length=255)),
                ('originating_outreach', models.CharField(choices=[('bible_work', 'Bible Work'), ('medical_missionary', 'Medical Missionary'), ('other', 'Other')], default='other', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('assigned_follower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_to_nurture', to='nurture.churchmember')),
            ],
        ),
        migrations.CreateModel(
            name='FollowUpInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('method', models.CharField(choices=[('phone_call', 'Phone Call'), ('home_visit', 'Home Visit'), ('email', 'Email'), ('group_meeting', 'Group Meeting'), ('other', 'Other')], max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='nurture.baptizedmember')),
            ],
        ),
    ]
